package com.grts.dao;

import com.grts.pojo.CustomerBean;

public interface CustomerBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Wed Nov 07 17:05:21 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Wed Nov 07 17:05:21 CST 2018
     */
    int insert(CustomerBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Wed Nov 07 17:05:21 CST 2018
     */
    int insertSelective(CustomerBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Wed Nov 07 17:05:21 CST 2018
     */
    CustomerBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Wed Nov 07 17:05:21 CST 2018
     */
    int updateByPrimaryKeySelective(CustomerBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbggenerated Wed Nov 07 17:05:21 CST 2018
     */
    int updateByPrimaryKey(CustomerBean record);
}