package com.grts.pojo;

public class DataBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data.id
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data.name
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data.memo
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_data.pid
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data.id
     *
     * @return the value of t_data.id
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data.id
     *
     * @param id the value for t_data.id
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data.name
     *
     * @return the value of t_data.name
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data.name
     *
     * @param name the value for t_data.name
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data.memo
     *
     * @return the value of t_data.memo
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data.memo
     *
     * @param memo the value for t_data.memo
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_data.pid
     *
     * @return the value of t_data.pid
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_data.pid
     *
     * @param pid the value for t_data.pid
     *
     * @mbggenerated Tue Nov 06 17:34:11 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}