package com.grts.pojo;

public class DeptBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.id
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.name
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.memo
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.id
     *
     * @return the value of t_dept.id
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.id
     *
     * @param id the value for t_dept.id
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.name
     *
     * @return the value of t_dept.name
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.name
     *
     * @param name the value for t_dept.name
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.memo
     *
     * @return the value of t_dept.memo
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.memo
     *
     * @param memo the value for t_dept.memo
     *
     * @mbggenerated Fri Nov 02 17:37:11 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}