package com.grts.pojo;

public class WorkAttachBean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_workattach.id
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_workattach.newfilename
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	private String newfilename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_workattach.oldfilename
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	private String oldfilename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_workattach.workid
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	private String workid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_workattach.id
	 * @return  the value of t_workattach.id
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_workattach.id
	 * @param id  the value for t_workattach.id
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_workattach.newfilename
	 * @return  the value of t_workattach.newfilename
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public String getNewfilename() {
		return newfilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_workattach.newfilename
	 * @param newfilename  the value for t_workattach.newfilename
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public void setNewfilename(String newfilename) {
		this.newfilename = newfilename == null ? null : newfilename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_workattach.oldfilename
	 * @return  the value of t_workattach.oldfilename
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public String getOldfilename() {
		return oldfilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_workattach.oldfilename
	 * @param oldfilename  the value for t_workattach.oldfilename
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public void setOldfilename(String oldfilename) {
		this.oldfilename = oldfilename == null ? null : oldfilename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_workattach.workid
	 * @return  the value of t_workattach.workid
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public String getWorkid() {
		return workid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_workattach.workid
	 * @param workid  the value for t_workattach.workid
	 * @mbggenerated  Wed Nov 07 17:04:23 CST 2018
	 */
	public void setWorkid(String workid) {
		this.workid = workid == null ? null : workid.trim();
	}
}